version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - /react-app/node_modules
      - ./:/react-app

  react-app-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /react-app/node_modules
      - ./:/react-app
    command: ["npm", "run", "test"]