FROM node:21-alpine as builder

WORKDIR /react-app

COPY ./package.json ./

RUN npm i

COPY ./ ./

RUN npm run build


FROM nginx:stable-alpine

COPY --from=builder /react-app/dist /usr/share/nginx/html