name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: unit-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -f Dockerfile.dev . -t react-app/unit-test

      - name: Run unit tests
        run: docker run react-app/unit-test npm run test
