name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: unit-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v5

      # - name: Run tests in Docker container
      #   run: docker run -e CI=true docker-react npm run test
  
