name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: unit-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile.prod
          push: false  # Set to true if you want to push the image

      # You can add additional steps here, e.g., running tests in the Docker container.
